### ISSUE TITLE
DSP_INIT may not contain a valid patch

### ISSUE THREAD

**Issue by bobaruni** [marsel90-1/TEF6686_Arduino_Radio#1]
The patch array @ DSP_INIT[] does not contain the usual start of a patch such as: 
03 1C 00 00 
03 1C 00 74
After the patch is applied, the TEF6686 still has the standard firmware version number confirmed by performing APPL_Get_Identification (40 82 01)
The returned value is 090E 0100 0200 0000 = TEF6686 Hardware version 1.0, software version 2.00, patch version 0.00

Patch 2.22 has a returned value of 090E 0100 0200 0216 = TEF6686 Hardware version 1.0, software version 2.00, patch 02.22
Patch 2.24 has a returned value of 090E 0100 0200 0218 = TEF6686 Hardware version 1.0, software version 2.00, patch 02.24

How was patch 5.12 created, is it working but without registering the patch number?

**Comment by marsel90-1** [comment]
Tuner_Patch_Lithio_V205_p512.h
Catena / NXP semiconductors
Creation date:  2017.08.25
Version: 5.00 - p5.12

**Comment by bobaruni** [comment]
Thanks for the info Marsel.
Since this is Catena patch code, it should work unless it is only for a version V205 chip (the latest version of TEF6686)
I have tested the latest commit on my TEF6686 V102 chip and cannot get the patch to work.
I have tried various changes to INIT_FLAG_PATCH1 and INIT_FLAG_PATCH2 but it will not work on my chip.
The TEF6686 acts as if no patch was applied, almost everything works, stations can be tuned as normal but some commands are missing.
The section of the patch that causes a reset (0x05, 0x1E, 0x5A, 0x01, 0x5A, 0x5A) works, as does everything after start firmware (0x03, 0x14, 0x00, 0x01).
One way to verify that the patch doesn't work is that commands that only work after a patch is applied don't work with patch p512.
Example, Get_Signal_Status (0x21, 0x85, 0x01) returns 0 for the noise level, but with any working patch (p209 onwards), the noise level is returned correctly - this feature was first implemented in V102_P209
The other way I test if the patch is working is by performing a APPL_Get_Identification (0x40, 0x82, 0x01)
which returns no patch information or patch not loaded - (0x00, 0x00) last 2 bytes of (090E 0100 0200 0000)
Is there any mention in the literature, Is it possible the patch code is only for V205 chip?
I hope this helps.

**Comment by marsel90-1** [comment]
I didn't find anything about the chip version. Only tab with init and patch.
Thank you for the information. I decided to delete the draft version that contains this pach.

**Comment by bobaruni** [comment]
Don't give up, it's very hard with the complete lack of information about these patches.
I bet it will work on the newer v205 chips.
If you wanted to support both, you could query the chip version then apply p2.24 if it's v102 or apply p5.12 if it's v205 chip, that is if there is enough room for an extra patch on an Arduino Nano.
I will try and get a newer v205 chip and test.
